services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}

  redis:
    image: redis:alpine

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${POSTGRES_DB}

volumes:
  db_data:
