default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: db


production:
  primary: &primary_production
    <<: *default
    database:
    username:
    password:
  cache:
    <<: *primary_production
    database: bens_pdf_module_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: bens_pdf_module_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: bens_pdf_module_production_cable
    migrations_paths: db/cable_migrate
